### ISSUE TITLE
dmesg刷屏了，基本都是gpu驱动崩溃信息

### ISSUE THREAD

**Issue by txlos** [redroid-rockchip/.github#1]
是不是gpu定义成g52有兼容问题？

**Comment by ice-black-tea** [comment]
> 是不是gpu定义成g52有兼容问题？

应该不是，我装的不是桌面版系统，没有出现你情况，下面是我环境信息

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

$ uname -a
Linux rock-5b 5.10.110-99-rockchip-gf45941622 #rockchip SMP Sun Mar 3 15:31:08 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by doduhuang** [comment]
> > 是不是gpu定义成g52有兼容问题？
> 
> 应该不是，我装的不是桌面版系统，没有出现你情况，下面是我环境信息
> 
> ```shell
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.04 LTS
> Release:	22.04
> Codename:	jammy
> 
> $ uname -a
> Linux rock-5b 5.10.110-99-rockchip-gf45941622 #rockchip SMP Sun Mar 3 15:31:08 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
> ```

请问您的ubuntu 这个版本，就是用的jammy ，并没有改过内核 吗？ 要不要手动编译内核 ，开启一些选项

**Comment by ice-black-tea** [comment]
> > > 是不是gpu定义成g52有兼容问题？
> > 
> > 
> > 应该不是，我装的不是桌面版系统，没有出现你情况，下面是我环境信息
> > ```shell
> > $ lsb_release -a
> > No LSB modules are available.
> > Distributor ID:	Ubuntu
> > Description:	Ubuntu 22.04 LTS
> > Release:	22.04
> > Codename:	jammy
> > 
> > $ uname -a
> > Linux rock-5b 5.10.110-99-rockchip-gf45941622 #rockchip SMP Sun Mar 3 15:31:08 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
> > ```
> 
> 请问您的ubuntu 这个版本，就是用的jammy ，并没有改过内核 吗？ 要不要手动编译内核 ，开启一些选项

内核有编译好的，https://github.com/redroid-rockchip/kernel-rock5b/releases/tag/5.10.110-99-rockchip-20240303

**Comment by doduhuang** [comment]
> > > > 是不是gpu定义成g52有兼容问题？
> > > 
> > > 
> > > 应该不是，我装的不是桌面版系统，没有出现你情况，下面是我环境信息
> > > ```shell
> > > $ lsb_release -a
> > > No LSB modules are available.
> > > Distributor ID:	Ubuntu
> > > Description:	Ubuntu 22.04 LTS
> > > Release:	22.04
> > > Codename:	jammy
> > > 
> > > $ uname -a
> > > Linux rock-5b 5.10.110-99-rockchip-gf45941622 #rockchip SMP Sun Mar 3 15:31:08 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
> > > ```
> > 
> > 
> > 请问您的ubuntu 这个版本，就是用的jammy ，并没有改过内核 吗？ 要不要手动编译内核 ，开启一些选项
> 
> 内核有编译好的，https://github.com/redroid-rockchip/kernel-rock5b/releases/tag/5.10.110-99-rockchip-20240303

我下载了 https://github.com/redroid-rockchip/kernel-rock5b/releases/tag/5.10.110-99-rockchip-20240303 这个内核 ，也通过了sudo dpkg -i  安装了他，但是无法切换过去，还是系统默认的 5.10.160-rockchip  该如何解决， 查看官方说修改/boot/extlinux/extlinux.conf. 但是并没有这个文 件

**Comment by doduhuang** [comment]
> > 是不是gpu定义成g52有兼容问题？
> 
> 应该不是，我装的不是桌面版系统，没有出现你情况，下面是我环境信息
> 
> ```shell
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.04 LTS
> Release:	22.04
> Codename:	jammy
> 
> $ uname -a
> Linux rock-5b 5.10.110-99-rockchip-gf45941622 #rockchip SMP Sun Mar 3 15:31:08 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
> ```

可否给一下您下载的 Ubuntu 22.04 连接，我这里下载https://github.com/Joshua-Riek/ubuntu-rockchip/releases v1.33版本22.04.3 无法更新您提供的内核（ https://github.com/redroid-rockchip/kernel-rock5b/releases/tag/5.10.110-99-rockchip-20240303 ） 。

**Comment by ice-black-tea** [comment]
> > > 是不是gpu定义成g52有兼容问题？
> > 
> > 
> > 应该不是，我装的不是桌面版系统，没有出现你情况，下面是我环境信息
> > ```shell
> > $ lsb_release -a
> > No LSB modules are available.
> > Distributor ID:	Ubuntu
> > Description:	Ubuntu 22.04 LTS
> > Release:	22.04
> > Codename:	jammy
> > 
> > $ uname -a
> > Linux rock-5b 5.10.110-99-rockchip-gf45941622 #rockchip SMP Sun Mar 3 15:31:08 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
> > ```
> 
> 可否给一下您下载的 Ubuntu 22.04 连接，我这里下载https://github.com/Joshua-Riek/ubuntu-rockchip/releases v1.33版本22.04.3 无法更新您提供的内核（ https://github.com/redroid-rockchip/kernel-rock5b/releases/tag/5.10.110-99-rockchip-20240303 ） 。

没记错的话我用的是 [rock-5b_ubuntu_jammy_cli_b39.img.xz](https://github.com/radxa-build/rock-5b/releases/tag/b39)
