### ISSUE TITLE
开启了虚拟wifi为什么不能adb connect 连不上 

### ISSUE THREAD

**Issue by doduhuang** [redroid-rockchip/.github#3]
开启了虚拟wifi为什么不能adb connect ，这样无法使用qtscrcpy了。有其它方法吗，或者怎么解决这个问题。感谢您解惑

**Comment by ice-black-tea** [comment]
首先确保开启了mac80211_hwsim内核模块，并且将iptables切成iptables-legacy

确认没问题，然后进docker容器，通过下面两条命令查看网卡是否正确初始化
```
ifconfig    # 包含wlan0、radio0
/vendor/bin/execns2 router ifconfig    # 包含radio0-peer、wlan1、eth0
```

如果网卡也没问题的话，就需要拉一下logcat日志了

**Comment by doduhuang** [comment]
![微信截图_20240426214131](https://github.com/redroid-rockchip/.github/assets/39383187/bfc26c04-b841-4a80-bfbc-0c0e083ba72f)
![微信截图_20240426214149](https://github.com/redroid-rockchip/.github/assets/39383187/67b2cb52-cf80-45a7-85a6-701b84af9d3f)
[log.txt](https://github.com/redroid-rockchip/.github/files/15131353/log.txt)
有的，我就是用的您 的 内核 包。

**Comment by doduhuang** [comment]
> 首先确保开启了mac80211_hwsim内核模块，并且将iptables切成iptables-legacy
> 
> 确认没问题，然后进docker容器，通过下面两条命令查看网卡是否正确初始化
> 
> ```
> ifconfig    # 包含wlan0、radio0
> /vendor/bin/execns2 router ifconfig    # 包含radio0-peer、wlan1、eth0
> ```
> 
> 如果网卡也没问题的话，就需要拉一下logcat日志了

上面附件里，有log 。

**Comment by ice-black-tea** [comment]
> > 首先确保开启了mac80211_hwsim内核模块，并且将iptables切成iptables-legacy
> > 确认没问题，然后进docker容器，通过下面两条命令查看网卡是否正确初始化
> > ```
> > ifconfig    # 包含wlan0、radio0
> > /vendor/bin/execns2 router ifconfig    # 包含radio0-peer、wlan1、eth0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果网卡也没问题的话，就需要拉一下logcat日志了
> 
> 上面附件里，有log 。

虚拟wifi没看出来有啥问题，gpu倒是有点问题，把[mali_csffw.bin.zip](https://github.com/redroid-rockchip/.github/files/15131434/mali_csffw.bin.zip)解压出来，放在宿主机的/lib/firmware中，然后重启板子试试

还不行的话把androidboot.redroid_virtual_wifi=1去掉，先看看不开虚拟wifi能不能正常启动

**Comment by doduhuang** [comment]
> > > /vendor/bin/execns2 router ifconfig
> > 
> > 
> > 谢谢你的提醒，已将mali_csffw.bin 放入了，目前去掉androidboot.redroid_virtual_wifi=1 可以正常连接的。，麻烦您 再看一下。 为什么本地局域网连不上，本地adb connect 127.0.0.1:5555这样，却可以连接上！！！附件里有完整的日 记， [log2.txt](https://github.com/redroid-rockchip/.github/files/15137637/log2.txt)
> 
> 日志看容器启动没啥问题，局域网访问不了的问题需要你自己折腾折腾了

拆腾了二天，现在参考 https://github.com/CNflysky/redroid-rk3588（基于您的项目改的） 这位大佬的虚拟wifi项目可以开启虚拟wifi的时候 局域网连上。不过我修改的文 件编译出来后，可以显示虚拟wifi了，不过一直会连续在连接。 附件里，我提取了项目的虚拟wifi文件。如果能解决这bug就太好了。
[虚拟wifi文件参考.zip](https://github.com/redroid-rockchip/.github/files/15142169/wifi.zip)

运行报错的log
[log.txt](https://github.com/redroid-rockchip/.github/files/15142177/log.txt)

**Comment by ice-black-tea** [comment]
> > > > /vendor/bin/execns2 router ifconfig
> > > 
> > > 
> > > 谢谢你的提醒，已将mali_csffw.bin 放入了，目前去掉androidboot.redroid_virtual_wifi=1 可以正常连接的。，麻烦您 再看一下。 为什么本地局域网连不上，本地adb connect 127.0.0.1:5555这样，却可以连接上！！！附件里有完整的日 记， [log2.txt](https://github.com/redroid-rockchip/.github/files/15137637/log2.txt)
> > 
> > 
> > 日志看容器启动没啥问题，局域网访问不了的问题需要你自己折腾折腾了
> 
> 拆腾了二天，现在参考 [https://github.com/CNflysky/redroid-rk3588（基于您的项目改的）](https://github.com/CNflysky/redroid-rk3588%EF%BC%88%E5%9F%BA%E4%BA%8E%E6%82%A8%E7%9A%84%E9%A1%B9%E7%9B%AE%E6%94%B9%E7%9A%84%EF%BC%89) 这位大佬的虚拟wifi项目可以开启虚拟wifi的时候 局域网连上。不过我修改的文 件编译出来后，可以显示虚拟wifi了，不过一直会连续在连接。 附件里，我提取了项目的虚拟wifi文件。如果能解决这bug就太好了。 [虚拟wifi文件参考.zip](https://github.com/redroid-rockchip/.github/files/15142169/wifi.zip)
> 
> 运行报错的log [log.txt](https://github.com/redroid-rockchip/.github/files/15142177/log.txt)

这是基于我的 [老版本](https://github.com/redroid-rockchip/vendor_redroid_ext/blob/2dd164f504ba13be7aa69850ee2c47dfd9421cdf/wifi/init.wifi.rc) 改的，虚拟wifi有一定概率无法正常初始化。你这环境我这复现不了，暂时还无法定位问题

**Comment by chenzhu005774** [comment]
> > > > /vendor/bin/execns2 router ifconfig
> > > 
> > > 
> > > 谢谢你的提醒，已将mali_csffw.bin 放入了，目前去掉androidboot.redroid_virtual_wifi=1 可以正常连接的。，麻烦您 再看一下。 为什么本地局域网连不上，本地adb connect 127.0.0.1:5555这样，却可以连接上！！！附件里有完整的日 记， [log2.txt](https://github.com/redroid-rockchip/.github/files/15137637/log2.txt)
> > 
> > 
> > 日志看容器启动没啥问题，局域网访问不了的问题需要你自己折腾折腾了
> 
> 拆腾了二天，现在参考 [https://github.com/CNflysky/redroid-rk3588（基于您的项目改的）](https://github.com/CNflysky/redroid-rk3588%EF%BC%88%E5%9F%BA%E4%BA%8E%E6%82%A8%E7%9A%84%E9%A1%B9%E7%9B%AE%E6%94%B9%E7%9A%84%EF%BC%89) 这位大佬的虚拟wifi项目可以开启虚拟wifi的时候 局域网连上。不过我修改的文 件编译出来后，可以显示虚拟wifi了，不过一直会连续在连接。 附件里，我提取了项目的虚拟wifi文件。如果能解决这bug就太好了。 [虚拟wifi文件参考.zip](https://github.com/redroid-rockchip/.github/files/15142169/wifi.zip)
> 
> 运行报错的log [log.txt](https://github.com/redroid-rockchip/.github/files/15142177/log.txt)

请问你解决了吗 我现在开启虚拟WiFi也无法连接。去掉adb 就能连接

**Comment by chenzhu005774** [comment]
> > > > /vendor/bin/execns2 router ifconfig
> > > 
> > > 
> > > 谢谢你的提醒，已将mali_csffw.bin 放入了，目前去掉androidboot.redroid_virtual_wifi=1 可以正常连接的。，麻烦您 再看一下。 为什么本地局域网连不上，本地adb connect 127.0.0.1:5555这样，却可以连接上！！！附件里有完整的日 记， [log2.txt](https://github.com/redroid-rockchip/.github/files/15137637/log2.txt)
> > 
> > 
> > 日志看容器启动没啥问题，局域网访问不了的问题需要你自己折腾折腾了
> 
> 拆腾了二天，现在参考 [https://github.com/CNflysky/redroid-rk3588（基于您的项目改的）](https://github.com/CNflysky/redroid-rk3588%EF%BC%88%E5%9F%BA%E4%BA%8E%E6%82%A8%E7%9A%84%E9%A1%B9%E7%9B%AE%E6%94%B9%E7%9A%84%EF%BC%89) 这位大佬的虚拟wifi项目可以开启虚拟wifi的时候 局域网连上。不过我修改的文 件编译出来后，可以显示虚拟wifi了，不过一直会连续在连接。 附件里，我提取了项目的虚拟wifi文件。如果能解决这bug就太好了。 [虚拟wifi文件参考.zip](https://github.com/redroid-rockchip/.github/files/15142169/wifi.zip)
> 
> 运行报错的log [log.txt](https://github.com/redroid-rockchip/.github/files/15142177/log.txt)

请问你解决了嘛。我和你是一样得现象，目前去掉androidboot.redroid_virtual_wifi=1 可以正常连接。加上虚拟WiFi。为什么本地局域网连不上，本地adb connect 127.0.0.1:5555这样，却可以连接上。

**Comment by ice-black-tea** [comment]
经过确认开启虚拟wifi之后，局域网无法连接容器的主要原因是网段冲突了，目前已修改网关默认ip，也可自行添加androidboot.redroid_wifi_gateway参数配置网关ip，可以通过以下命令启动容器：

```
sudo docker run -itd --privileged \
    --name redroid \
    -v ~/redroid-data/data:/data \
    -v /dev/mali0:/dev/mali0 \
    -p 5555:5555 \
    iceblacktea/redroid-arm64:12.0.0-241115 \
    androidboot.redroid_gpu_mode=mali \
    androidboot.redroid_wifi=1 \
    androidboot.redroid_wifi_gateway=7.7.7.1/24 \
    androidboot.redroid_magisk=1
```

在此感谢 @chenzhu005774 提供的复现环境

**Comment by doduhuang** [comment]
> 经过确认开启虚拟wifi之后，局域网无法连接容器的主要原因是网段冲突了，目前已修改网关默认ip，也可自行添加androidboot.redroid_wifi_gateway参数配置网关ip，可以通过以下命令启动容器：
> 
> ```
> sudo docker run -itd --privileged \
>     --name redroid \
>     -v ~/redroid-data/data:/data \
>     -v /dev/mali0:/dev/mali0 \
>     -p 5555:5555 \
>     iceblacktea/redroid-arm64:12.0.0-241115 \
>     androidboot.redroid_gpu_mode=mali \
>     androidboot.redroid_wifi=1 \
>     androidboot.redroid_wifi_gateway=7.7.7.1/24 \
>     androidboot.redroid_magisk=1
> ```
> 
> 在此感谢 @chenzhu005774 提供的复现环境

感谢,另外,好像在某处看到的资料是因为我有wifi网卡的原因,你的环境应该没有,,无线网卡禁用+删除wlan1，虚拟wifi好像也没有问题了.
