### ISSUE TITLE
虚拟wifi开启后能连接到wifi但是上不了网（default route缺失?)

### ISSUE THREAD

**Issue by Frefreak** [redroid-rockchip/.github#4]
![image](https://github.com/redroid-rockchip/.github/assets/7122156/ef751607-7b44-46a6-bdcb-4ff40965bcad)

```bash
docker run -itd --rm --privileged \
        --pull always -v ~/data:/data \
        -v /dev/mali0:/dev/mali0 \
        -p 5555:5555 \
        iceblacktea/redroid-arm64:12.0.0-240328 \
        androidboot.redroid_gpu_mode=mali \
        androidboot.redroid_virtual_wifi=1
```

启动后能看到ChinaNet等4个wifi网络但是连上后都显示无法提供网络。

看了下`ip route`是这样的：
```
192.168.1.0/24 dev wlan0 proto kernel scope link src 192.168.1.2
192.168.200.0/24 dev radio0 proto kernel scope link src 192.168.200.2
```
但是如果手动加上default route就可以正常上网了
`ip route add default via 192.168.1.1`

作为对比如果启动时不加`redroid_virtual_wifi=1`好像就会自动生成一条default route规则，这时虽然没有wifi但是可以正常连接网络。

请问下default route缺失是预期的吗，可能是啥问题

**Comment by ice-black-tea** [comment]
理论上有默认路由才对
```
$ ip route show table wlan0
default via 192.168.1.1 dev wlan0 proto static
192.168.1.0/24 dev wlan0 proto static scope link
```

dhcpserver分配给wlan0的信息都对吗

**Comment by Frefreak** [comment]
```
redroid_arm64:/ $ ip route show table wlan0
Error: argument "wlan0" is wrong: table id value is invalid

255|redroid_arm64:/ $ ip route show table all
192.168.1.0/24 dev wlan0 proto kernel scope link src 192.168.1.2
192.168.200.0/24 dev radio0 proto kernel scope link src 192.168.200.2
broadcast 127.0.0.0 dev lo table local proto kernel scope link src 127.0.0.1
local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1
local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1
broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1
broadcast 192.168.1.0 dev wlan0 table local proto kernel scope link src 192.168.1.2
local 192.168.1.2 dev wlan0 table local proto kernel scope host src 192.168.1.2
broadcast 192.168.1.255 dev wlan0 table local proto kernel scope link src 192.168.1.2
broadcast 192.168.200.0 dev radio0 table local proto kernel scope link src 192.168.200.2
local 192.168.200.2 dev radio0 table local proto kernel scope host src 192.168.200.2
broadcast 192.168.200.255 dev radio0 table local proto kernel scope link src 192.168.200.2
local ::1 dev lo proto kernel metric 0 pref medium
local fe80::60e0:38ff:fef4:6a2c dev radio0 proto kernel metric 0 pref medium
local fe80::9243:461b:97e0:980 dev wlan0 proto kernel metric 0 pref medium
fe80::/64 dev radio0 proto kernel metric 256 pref medium
fe80::/64 dev wlan0 proto kernel metric 256 pref medium
multicast ff00::/8 dev radio0 proto kernel metric 256 pref medium
multicast ff00::/8 dev wlan0 proto kernel metric 256 pref medium
redroid_arm64:/ $ ip ad
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 02:2b:51:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.2/24 brd 192.168.1.255 scope global wlan0
       valid_lft forever preferred_lft forever
    inet6 fe80::9243:461b:97e0:980/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
4: radio0@if2: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 62:e0:38:f4:6a:2c brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet 192.168.200.2/24 brd 192.168.200.255 scope global radio0
       valid_lft forever preferred_lft forever
    inet6 fe80::60e0:38ff:fef4:6a2c/64 scope link
       valid_lft forever preferred_lft forever

```


> dhcpserver分配给wlan0的信息都对吗

这个应该怎么看

**Comment by ice-black-tea** [comment]
> ```
> redroid_arm64:/ $ ip route show table wlan0
> Error: argument "wlan0" is wrong: table id value is invalid
> 
> 255|redroid_arm64:/ $ ip route show table all
> 192.168.1.0/24 dev wlan0 proto kernel scope link src 192.168.1.2
> 192.168.200.0/24 dev radio0 proto kernel scope link src 192.168.200.2
> broadcast 127.0.0.0 dev lo table local proto kernel scope link src 127.0.0.1
> local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1
> local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1
> broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1
> broadcast 192.168.1.0 dev wlan0 table local proto kernel scope link src 192.168.1.2
> local 192.168.1.2 dev wlan0 table local proto kernel scope host src 192.168.1.2
> broadcast 192.168.1.255 dev wlan0 table local proto kernel scope link src 192.168.1.2
> broadcast 192.168.200.0 dev radio0 table local proto kernel scope link src 192.168.200.2
> local 192.168.200.2 dev radio0 table local proto kernel scope host src 192.168.200.2
> broadcast 192.168.200.255 dev radio0 table local proto kernel scope link src 192.168.200.2
> local ::1 dev lo proto kernel metric 0 pref medium
> local fe80::60e0:38ff:fef4:6a2c dev radio0 proto kernel metric 0 pref medium
> local fe80::9243:461b:97e0:980 dev wlan0 proto kernel metric 0 pref medium
> fe80::/64 dev radio0 proto kernel metric 256 pref medium
> fe80::/64 dev wlan0 proto kernel metric 256 pref medium
> multicast ff00::/8 dev radio0 proto kernel metric 256 pref medium
> multicast ff00::/8 dev wlan0 proto kernel metric 256 pref medium
> redroid_arm64:/ $ ip ad
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
>     inet6 ::1/128 scope host
>        valid_lft forever preferred_lft forever
> 2: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
>     link/ether 02:2b:51:00:00:00 brd ff:ff:ff:ff:ff:ff
>     inet 192.168.1.2/24 brd 192.168.1.255 scope global wlan0
>        valid_lft forever preferred_lft forever
>     inet6 fe80::9243:461b:97e0:980/64 scope link stable-privacy
>        valid_lft forever preferred_lft forever
> 4: radio0@if2: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
>     link/ether 62:e0:38:f4:6a:2c brd ff:ff:ff:ff:ff:ff link-netnsid 1
>     inet 192.168.200.2/24 brd 192.168.200.255 scope global radio0
>        valid_lft forever preferred_lft forever
>     inet6 fe80::60e0:38ff:fef4:6a2c/64 scope link
>        valid_lft forever preferred_lft forever
> ```
> 
> > dhcpserver分配给wlan0的信息都对吗
> 
> 这个应该怎么看

你那环境相较于我的环境确实少了default route，后续版本我脚本里主动添加一下default route来解决这个问题吧

**Comment by hjxcode** [comment]
你好，我也遇到了这个问题，请问解决了么？我的现象是显示连接wif，正在获取ip，但没办法真正连接上，容器内的route也是只有一条
![image](https://github.com/redroid-rockchip/.github/assets/52154374/c4cf0f89-6e82-45fb-a7c3-2f4d8ecc488f)

![image](https://github.com/redroid-rockchip/.github/assets/52154374/5d052eb5-7ab5-4bfb-8d23-63b66829f50f)

**Comment by jianglin-code** [comment]
虚拟wifi有下行网络，没有上行网络？

**Comment by chenzhu005774** [comment]
> 你好，我也遇到了这个问题，请问解决了么？我的现象是显示连接wif，正在获取ip，但没办法真正连接上，容器内的route也是只有一条 ![image](https://private-user-images.githubusercontent.com/52154374/337210004-c4cf0f89-6e82-45fb-a7c3-2f4d8ecc488f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjYzMDgsIm5iZiI6MTczMDk2NjAwOCwicGF0aCI6Ii81MjE1NDM3NC8zMzcyMTAwMDQtYzRjZjBmODktNmU4Mi00NWZiLWE3YzMtMmY0ZDhlY2M0ODhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA3NTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYjFjY2Y5OGQ5MmFhZTUzMWNiMDlmNjI0ZjRkZTBlOWI0NmE4YzQ3YWFkNjRiOTlhMDBmOWQ0MjBjNTI0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._P5en69u4kib_OSknF5kDuIxGRjmskMcT-lrB-XpsX4)
> 
> ![image](https://private-user-images.githubusercontent.com/52154374/337210107-5d052eb5-7ab5-4bfb-8d23-63b66829f50f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjYzMDgsIm5iZiI6MTczMDk2NjAwOCwicGF0aCI6Ii81MjE1NDM3NC8zMzcyMTAxMDctNWQwNTJlYjUtN2FiNS00YmZiLThkMjMtNjNiNjY4MjlmNTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA3NTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNTNjZWEzNTBkN2FhZGI5YzRiYmEyMzRiYzQzNGI5ZDgyNTE4ZjdmOGZhZTZjMTU4M2Q2MDg3YmEzNzE2ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1stEnSbYb8zLfcIWci-9xZkrdPA0z71AFvxnbRpMgT0)

你好请问 你解决了嘛

**Comment by hjxcode** [comment]
> > 你好，我也遇到了这个问题，请问解决了么？我的现象是显示连接wif，正在获取ip，但没办法真正连接上，容器内的route也是只有一条 ![image](https://private-user-images.githubusercontent.com/52154374/337210004-c4cf0f89-6e82-45fb-a7c3-2f4d8ecc488f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjYzMDgsIm5iZiI6MTczMDk2NjAwOCwicGF0aCI6Ii81MjE1NDM3NC8zMzcyMTAwMDQtYzRjZjBmODktNmU4Mi00NWZiLWE3YzMtMmY0ZDhlY2M0ODhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA3NTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYjFjY2Y5OGQ5MmFhZTUzMWNiMDlmNjI0ZjRkZTBlOWI0NmE4YzQ3YWFkNjRiOTlhMDBmOWQ0MjBjNTI0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._P5en69u4kib_OSknF5kDuIxGRjmskMcT-lrB-XpsX4)
> > ![image](https://private-user-images.githubusercontent.com/52154374/337210107-5d052eb5-7ab5-4bfb-8d23-63b66829f50f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjYzMDgsIm5iZiI6MTczMDk2NjAwOCwicGF0aCI6Ii81MjE1NDM3NC8zMzcyMTAxMDctNWQwNTJlYjUtN2FiNS00YmZiLThkMjMtNjNiNjY4MjlmNTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA3NTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNTNjZWEzNTBkN2FhZGI5YzRiYmEyMzRiYzQzNGI5ZDgyNTE4ZjdmOGZhZTZjMTU4M2Q2MDg3YmEzNzE2ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1stEnSbYb8zLfcIWci-9xZkrdPA0z71AFvxnbRpMgT0)
> 
> 你好请问 你解决了嘛


Sorry, no. I gave up real wifi behavior and instead tricked the software into thinking I was connected to wifi.

**Comment by chenzhu005774** [comment]
> > > 你好，我也遇到了这个问题，请问解决了么？我的现象是显示连接wif，正在获取ip，但没办法真正连接上，容器内的route也是只有一条 ![image](https://private-user-images.githubusercontent.com/52154374/337210004-c4cf0f89-6e82-45fb-a7c3-2f4d8ecc488f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjYzMDgsIm5iZiI6MTczMDk2NjAwOCwicGF0aCI6Ii81MjE1NDM3NC8zMzcyMTAwMDQtYzRjZjBmODktNmU4Mi00NWZiLWE3YzMtMmY0ZDhlY2M0ODhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA3NTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYjFjY2Y5OGQ5MmFhZTUzMWNiMDlmNjI0ZjRkZTBlOWI0NmE4YzQ3YWFkNjRiOTlhMDBmOWQ0MjBjNTI0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._P5en69u4kib_OSknF5kDuIxGRjmskMcT-lrB-XpsX4)
> > > ![image](https://private-user-images.githubusercontent.com/52154374/337210107-5d052eb5-7ab5-4bfb-8d23-63b66829f50f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjYzMDgsIm5iZiI6MTczMDk2NjAwOCwicGF0aCI6Ii81MjE1NDM3NC8zMzcyMTAxMDctNWQwNTJlYjUtN2FiNS00YmZiLThkMjMtNjNiNjY4MjlmNTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA3NTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNTNjZWEzNTBkN2FhZGI5YzRiYmEyMzRiYzQzNGI5ZDgyNTE4ZjdmOGZhZTZjMTU4M2Q2MDg3YmEzNzE2ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1stEnSbYb8zLfcIWci-9xZkrdPA0z71AFvxnbRpMgT0)
> > 
> > 
> > 你好请问 你解决了嘛
> 
> Sorry, no. I gave up real wifi behavior and instead tricked the software into thinking I was connected to wifi.
那冒昧的问一下。你这边 是怎么改动的呢，

**Comment by hjxcode** [comment]
> > > > 你好，我也遇到了这个问题，请问解决了么？我的现象是显示连接wif，正在获取ip，但没办法真正连接上，容器内的route也是只有一条 ![image](https://private-user-images.githubusercontent.com/52154374/337210004-c4cf0f89-6e82-45fb-a7c3-2f4d8ecc488f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjYzMDgsIm5iZiI6MTczMDk2NjAwOCwicGF0aCI6Ii81MjE1NDM3NC8zMzcyMTAwMDQtYzRjZjBmODktNmU4Mi00NWZiLWE3YzMtMmY0ZDhlY2M0ODhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA3NTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYjFjY2Y5OGQ5MmFhZTUzMWNiMDlmNjI0ZjRkZTBlOWI0NmE4YzQ3YWFkNjRiOTlhMDBmOWQ0MjBjNTI0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._P5en69u4kib_OSknF5kDuIxGRjmskMcT-lrB-XpsX4)
> > > > ![image](https://private-user-images.githubusercontent.com/52154374/337210107-5d052eb5-7ab5-4bfb-8d23-63b66829f50f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjYzMDgsIm5iZiI6MTczMDk2NjAwOCwicGF0aCI6Ii81MjE1NDM3NC8zMzcyMTAxMDctNWQwNTJlYjUtN2FiNS00YmZiLThkMjMtNjNiNjY4MjlmNTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA3NTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNTNjZWEzNTBkN2FhZGI5YzRiYmEyMzRiYzQzNGI5ZDgyNTE4ZjdmOGZhZTZjMTU4M2Q2MDg3YmEzNzE2ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1stEnSbYb8zLfcIWci-9xZkrdPA0z71AFvxnbRpMgT0)
> > > 
> > > 
> > > 你好请问 你解决了嘛
> > 
> > 
> > Sorry, no. I gave up real wifi behavior and instead tricked the software into thinking I was connected to wifi.
> > 那冒昧的问一下。你这边 是怎么改动的呢，

Modify the interface for obtaining wifi status in the source code, so that the return value is what I want to set.

**Comment by chenzhu005774** [comment]
> > > > 你好，我也遇到了这个问题，请问解决了么？我的现象是显示连接wif，正在获取ip，但没办法真正连接上，容器内的route也是只有一条 ![image](https://private-user-images.githubusercontent.com/52154374/337210004-c4cf0f89-6e82-45fb-a7c3-2f4d8ecc488f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjYzMDgsIm5iZiI6MTczMDk2NjAwOCwicGF0aCI6Ii81MjE1NDM3NC8zMzcyMTAwMDQtYzRjZjBmODktNmU4Mi00NWZiLWE3YzMtMmY0ZDhlY2M0ODhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA3NTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYjFjY2Y5OGQ5MmFhZTUzMWNiMDlmNjI0ZjRkZTBlOWI0NmE4YzQ3YWFkNjRiOTlhMDBmOWQ0MjBjNTI0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._P5en69u4kib_OSknF5kDuIxGRjmskMcT-lrB-XpsX4)
> > > > ![image](https://private-user-images.githubusercontent.com/52154374/337210107-5d052eb5-7ab5-4bfb-8d23-63b66829f50f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjYzMDgsIm5iZiI6MTczMDk2NjAwOCwicGF0aCI6Ii81MjE1NDM3NC8zMzcyMTAxMDctNWQwNTJlYjUtN2FiNS00YmZiLThkMjMtNjNiNjY4MjlmNTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA3NTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNTNjZWEzNTBkN2FhZGI5YzRiYmEyMzRiYzQzNGI5ZDgyNTE4ZjdmOGZhZTZjMTU4M2Q2MDg3YmEzNzE2ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1stEnSbYb8zLfcIWci-9xZkrdPA0z71AFvxnbRpMgT0)
> > > 
> > > 
> > > 你好请问 你解决了嘛
> > 
> > 
> > Sorry, no. I gave up real wifi behavior and instead tricked the software into thinking I was connected to wifi.
> > 那冒昧的问一下。你这边 是怎么改动的呢，

是这样的嘛？https://github.com/CNflysky/redroid-rk3588/wiki/zh:-%E5%85%B3%E4%BA%8E%E8%99%9A%E5%81%87WiFi

**Comment by jianglin-code** [comment]
可以完美解决，需要帮扶？

**Comment by jianglin-code** [comment]
可以完美解决，这个方案没问题，只是有些BUG要处理，需要帮扶？

**Comment by chenzhu005774** [comment]
> 可以完美解决，这个方案没问题，只是有些BUG要处理，需要帮扶？

是的我在开启虚拟WiFi的时候遇到了问题：
1.首先宿主机上mac82011 WiFi仿真是开启了的。
![e38755f7292bdc2e1d5bacf108066e86](https://github.com/user-attachments/assets/f80b02f9-8517-4236-ad5a-dc91191288eb)
2 .在容器中 的两个空间的网络分别如下：
![cd9b7938540d8ed599bffb1b3304a3f5](https://github.com/user-attachments/assets/5d7b30d9-538d-4d41-ad14-4465535dbe65)
![43ebebfb5fba233aab118129d14b741e](https://github.com/user-attachments/assets/7af28fb9-0cbe-45f0-89eb-5681ec99cfe7)
3.问题是：
  3.1 容器中无法访问外网。ping 百度不通，不开虚拟WiFi的时候能够正常访问外网。
  3.2 adb无法连接 adb服务正常。当不开启虚拟WiFi的时候能够正常adb连接
  
![684d969b339e5e324a1fc38931144782](https://github.com/user-attachments/assets/1ab39d41-16fb-4541-a393-fc91451a359b)


如果可以的话请你帮忙分析一下。谢谢。如果可以的话 麻烦你加下qq1039173580 指导一下

**Comment by ice-black-tea** [comment]
已添加默认路由并添加了4g上网功能

```
sudo docker run -itd --privileged \
    --name redroid \
    -v ~/data:/data \
    -v /dev/mali0:/dev/mali0 \
    -p 5555:5555 \
    iceblacktea/redroid-arm64:12.0.0-241204 \
    androidboot.redroid_gpu_mode=mali \
    androidboot.redroid_radio=1 \
    androidboot.redroid_wifi=1 \
    androidboot.redroid_wifi_gateway=7.7.7.1/24 \
    androidboot.redroid_magisk=1
```

**Comment by cplasfwst** [comment]
我使用了androidboot.redroid_radio=1 命令，请问为什么没有4G网络，没有显示出来，请问4G网络需要开启MAC80211_HWSIM吗？
