### ISSUE TITLE
怎样给没有面具的redriod添加面具

### ISSUE THREAD

**Issue by 124ffee** [redroid-rockchip/.github#6]
能告诉我一些思路吗？谢谢！！！

**Comment by ice-black-tea** [comment]
我是直接打包到镜像中的，可以参考 [https://github.com/redroid-rockchip/vendor_magisk](https://github.com/redroid-rockchip/vendor_magisk)

当然也可以将magisk.rc、magisk.apk、rootfs/vendor/etc/init/magisk文件参照仓库配置的路径放到redroid的指定路径
