### ISSUE TITLE
能否支持rk3566

### ISSUE THREAD

**Issue by kafuneri** [redroid-rockchip/.github#8]
rk3566用的gpu就是mali-G52，如果编译使用rk3566(香橙派3B)的sdk，应该可以在rk3566设备上使用吧，但我不是很懂编译，搞半天编不出来rk3566的镜像，如果可以，作者能否提供适用rk3566(的镜像，如果不行请直接关闭该Issues，打扰了。

**Comment by ice-black-tea** [comment]
可以先看看rk3588的镜像是否适用rk3566，顺带附上logcat

**Comment by kafuneri** [comment]
rk3566在/lib/firmware目录中没有mali驱动，即使是3566的panfrost驱动正常运行，也没有办法开启带gpu的redroid，用`gpu_mode=mail`的redroid-rockchip无法连接adb，`gpu_mode=guest`可以连接adb但是用scrcpy是一片黑屏，安装apk也失败，是没办法直接用了，用原版`redroid/redroid:11.0.0`镜像能使用cpu运行，虽然很卡，凑合能用；仔细想来rk3566的性能用上gpu也聊胜于无，还是升级设备吧

**Comment by Lua12138** [comment]
是可以的，都是G52，小修改就行。不过我这是在Android里运行的redroid，会麻烦不少。

如果你直接在Linux里跑，肯定也没啥问题。

![Image](https://github.com/user-attachments/assets/530bec98-c9bc-4d18-89b5-92542b5c86eb)
